export POSTGRESQL_HOST=${POSTGRESQL_HOST:=localhost}
export POSTGRESQL_PORT=${POSTGRESQL_PORT:=5432}
export POSTGRESQL_DBNAME=${POSTGRESQL_DBNAME:=quiz_dev}
export POSTGRESQL_USER=${POSTGRESQL_USER:=postgres}
export POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:=trustme}
export SQITCH_DEPLOY=${SQITCH_DEPLOY:=docker}
export API_WORKERS=${API_WORKERS:=1}
export API_PORT=${API_PORT:=8080}
